#ifndef DOODAD_H
#define DOODAD_H

#include <glm/glm.hpp>
#include <GL/glew.h>
#include "SceneGraph.hpp"
#include "Texture.hpp"
#include "Shader.hpp"

class Doodad : public Group
{ // a Doodad is a thing that can be generated by L-systems
};

class Segment : public Drawable
{
public:
  Segment(float length, float topScale, float bottomScale);
  void draw();

  std::shared_ptr<Shader> shader;
private:
  GLTexture tex;
  GLuint VAO;
  GLuint VBO;
  GLuint EBO;

  size_t indices;
};

#endif
